ARG OLAH_SOURCE=olah==0.5.2

FROM python:3.12

ARG OLAH_SOURCE

WORKDIR /app

RUN pip3 install --upgrade pip

RUN pip install --no-cache-dir ${OLAH_SOURCE}

EXPOSE 8090

VOLUME /data/repos
VOLUME /data/mirrors

ENTRYPOINT [ "olah-cli" ]

CMD ["--host", "0.0.0.0", "--repos-path", "/data/repos"]
